### ISSUE TITLE
Doesn't compile on windows

### ISSUE THREAD

**Issue by hardliner66** [adilbaig/gelfd#2]
dub\packages\gelfd-1.2.3\source\gelf\protocol.d(38,11): Error: undefined identifier 'LOG_ALERT'

The log levels defined in core.sys.posix.syslog are not available on windows.

**Comment by adilbaig** [comment]
Hey @hardliner66. Thanks for the report. I have released v1.3.0 with hardcoded syslevels. Could you please report back if it works for you.

Adil

**Comment by hardliner66** [comment]
I just tried it and it works. Thanks for the quick response and fix.
